### ISSUE TITLE
想问一下为什么不能实现直接从 Integer 转 Enum ?

### ISSUE THREAD

**Issue by kid1412621** [test-project-demos/spring-boot-get-post-enum-param#1]
而是必须从 String 先转 Integer

**Comment by cnfn** [comment]
> 而是必须从 String 先转 Integer

Spring 框架在处理 HTTP 参数的大致步骤:
1. 解析在代码中声明的参数名称和类型, 及其自定义的类型转换方法;
2. 解析在调用 HTTP 接口时传递的参数名称和值;
3. 使用第一步得到的类型信息做加工转换第二步得到 HTTP 参数值, 使其转换为程序中声明的类型;

其中在第二步获取解析 HTTP 参数值时, 调用了 [org.springframework.web.method.annotation.RequestParamMethodArgumentResolver#resolveName](https://github.com/spring-projects/spring-framework/blob/v5.0.10.RELEASE/spring-web/src/main/java/org/springframework/web/method/annotation/RequestParamMethodArgumentResolver.java#L181) 方法:
![image](https://user-images.githubusercontent.com/1445517/50053161-faf48200-016a-11e9-8afe-4948a505b86d.png)

它在 181 行通过调用 `org.springframework.web.context.request.WebRequest#getParameterValues` 方法获取到的 HTTP 参数值是字符串类型, 其声明为:
![image](https://user-images.githubusercontent.com/1445517/50053080-a00e5b00-0169-11e9-91ed-b1357f92db0f.png)

所以, 第二步 Spring 获取到 HTTP 参数值是 `String` 类型, 因此我们在自定义类型转换类时要将其 `source` 参数类型声明为 `String`.

当然, 在 Enum 类中, 除了支持通过整型获取枚举值外, 也可以重载一个接收 `String` 类型的方法...
